In [1]:
import json
import pandas as pd

# Let's load the dataset from Renthop right away
with open('train.json', 'r') as raw_data:
    data = json.load(raw_data)
    df = pd.DataFrame(data)

## Feature extraction

### Bag of Words example

In [5]:
from functools import reduce
import numpy as np

texts = [['i', 'have', 'a', 'cat'], 
        ['he', 'have', 'a', 'dog'], 
        ['he', 'and', 'i', 'have', 'a', 'cat', 'and', 'a', 'dog']]

dictionary = list(enumerate(set(list(reduce(lambda x, y: x + y, texts)))))

def vectorize(text): 
    vector = np.zeros(len(dictionary)) 
    for i, word in dictionary: 
        num = 0 
        for w in text: 
            if w == word: 
                num += 1 
        if num: 
            vector[i] = num 
    return vector

for t in texts: 
    print(vectorize(t))

[1. 0. 0. 1. 1. 1. 0.]
[0. 0. 1. 1. 1. 0. 1.]
[1. 2. 1. 1. 2. 1. 1.]


In [9]:
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer(ngram_range=(1,1))

vect.fit_transform(['no i have cows', 'i have no cows']).toarray(), vect.vocabulary_

(array([[1, 1, 1],
        [1, 1, 1]], dtype=int64), {'cows': 0, 'have': 1, 'no': 2})

In [10]:
vect = CountVectorizer(ngram_range=(1,2))

vect.fit_transform(['no i have cows', 'i have no cows']).toarray(), vect.vocabulary_

(array([[1, 1, 1, 0, 1, 0, 1],
        [1, 1, 0, 1, 1, 1, 0]], dtype=int64),
 {'cows': 0,
  'have': 1,
  'have cows': 2,
  'have no': 3,
  'no': 4,
  'no cows': 5,
  'no have': 6})